// external
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";

//internal
import Image from "next/image";
import Link from "next/link";
import NavLinks from "@/components/NavLinks";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-[#F9F6F0] text-[#1a1a1a] overflow-y-scroll">
        <header className="flex items-center justify-between px-8 py-4">
          <div className="flex items-center gap-2">
            <Image
              src="/book.png"
              alt="Bookified logo"
              width={28}
              height={28}
            />
            <span className="font-bold text-lg tracking-tight">Bookified</span>
          </div>
          <NavLinks />
        </header>
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
